#!/bin/bash
set -e
VERSION="$(< ./release)"

# Crea e passa a un ramo upstream temporaneo
git checkout -b upstream

# Rimuovi la cartella debian e fai commit
git rm -r -f debian/
git commit -m "Isolating clean source for v$VERSION"

# Crea il tag su questo commit pulito
git tag $VERSION

# Crea l'archivio da questo tag
git archive --format=tar.gz --prefix=penguins-bootloaders-$VERSION/ -o ../penguins-bootloaders_$VERSION.orig.tar.gz $VERSION
