#!/bin/bash
set -e
VERSION="$(< ./release)"

# Aggiorna il changelog alla nuova versione
dch -v $VERSION "Aggiunto supporto per il bootloader XYZ."

# Fai il commit di questa modifica
git add debian/changelog
git commit -m "Release v$VERSION"

# (Opzionale ma consigliato) Crea un tag per questa versione
git tag $VERSION