# File per GRUB (solo BIOS e UEFI 32-bit)
usr/lib/grub/i386-pc      usr/lib/penguins-bootloaders/grub
# Potresti voler includere anche i file da grub-efi-ia32-bin se necessario
# Esempio: usr/lib/grub/i386-efi usr/lib/penguins-bootloaders/grub

# File per ISOLINUX
usr/lib/ISOLINUX/isolinux.bin   usr/lib/penguins-bootloaders/ISOLINUX

# File per PXELINUX
usr/lib/PXELINUX/pxelinux.0     usr/lib/penguins-bootloaders/PXELINUX

# File per Syslinux
usr/lib/syslinux/modules/bios/*.c32   usr/lib/penguins-bootloaders/syslinux/modules/bios

# File per iPXE
# Nota: verifica il percorso esatto del file iPXE per i386. Potrebbe essere un .lkrn o altro.
usr/lib/ipxe/ipxe.lkrn          usr/lib/penguins-bootloaders/ipxe
