# File per GRUB
usr/lib/grub/i386-pc                usr/lib/penguins-bootloaders/grub
usr/lib/grub/x86_64-efi             usr/lib/penguins-bootloaders/grub
usr/lib/grub/x86_64-efi-signed      usr/lib/penguins-bootloaders/grub

# File per ISOLINUX
usr/lib/ISOLINUX/isolinux.bin   usr/lib/penguins-bootloaders/ISOLINUX

# File per PXELINUX
usr/lib/PXELINUX/pxelinux.0     usr/lib/penguins-bootloaders/PXELINUX
usr/lib/PXELINUX/lpxelinux.0     usr/lib/penguins-bootloaders/PXELINUX


# File per Syslinux (il wildcard funziona qui)
usr/lib/syslinux/modules/bios/*.c32   usr/lib/penguins-bootloaders/syslinux/modules/bios

# File per iPXE
usr/lib/ipxe/ipxe.efi           usr/lib/penguins-bootloaders/ipxe

# File per Shim
usr/lib/shim/shimx64.efi.signed usr/lib/penguins-bootloaders/shim
